// <auto-generated />
using System;
using ApplicationStatus.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationStatus.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250512035121_PrefixField")]
    partial class PrefixField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApplicationStatus.Models.ApiUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationName")
                        .IsUnique();

                    b.HasIndex("Prefix", "ApiKeyHash")
                        .IsUnique();

                    b.ToTable("ApiUsers");
                });

            modelBuilder.Entity("ApplicationStatus.Models.Heartbeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsGood")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationName")
                        .IsUnique();

                    b.ToTable("Heartbeats");
                });
#pragma warning restore 612, 618
        }
    }
}
